### ISSUE TITLE
Panic during run-time

### ISSUE THREAD

**Issue by Tmplt** [pajowu/signal-backup-decode#6]
I'm trying to decode a backup of mine via
```
$ signal-backup-decode signal.backup --password <password here> -o ./output --sqlite-path output/signal_backup.db
```
but the program panics with
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(MacVerificationError([194, 204, 123, 151, 76, 55, 140, 46, 209, 224], [253, 246, 15, 47, 113, 232, 242, 69, 170, 179]), State { next_error: None, backtrace: None })', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
The full backtrace is
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(MacVerificationError([194, 204, 123, 151, 76, 55, 140, 46, 209, 224], [253, 246, 15, 47, 113, 232, 242, 69, 170, 179]), State { next_error: None, backtrace: Some(stack backtrace:
   0:     0x55a12b78117c - backtrace::backtrace::trace::he728e6ef10b935e6
   1:     0x55a12b77f962 - backtrace::capture::Backtrace::new::hbd58f32db1ed86b2
   2:     0x55a12b77f42c - error_chain::make_backtrace::h676979fcf0f007e9
   3:     0x55a12b77f4c4 - <error_chain::State as core::default::Default>::default::ha763fbb7fe962285
   4:     0x55a12b709f03 - signal_backup_decode::decode_backup::h595a8b1b2f703127
   5:     0x55a12b70f5ee - signal_backup_decode::main::hb736c6f2fd77a4dc
   6:     0x55a12b6ee68f - std::rt::lang_start::{{closure}}::hb3961786ec22dc30
   7:     0x55a12b836bb7 - std::rt::lang_start_internal::{{closure}}::h37a0d646c7ead5f1
                        at libstd/rt.rs:59
                         - std::panicking::try::do_call::h55cb461590d952a0
                        at libstd/panicking.rs:306
   8:     0x55a12b846cee - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
   9:     0x55a12b833e55 - std::panicking::try::h574caffccc6046bb
                        at libstd/panicking.rs:285
                         - std::panic::catch_unwind::hf36d26a940fa3427
                        at libstd/panic.rs:361
                         - std::rt::lang_start_internal::h8627970b5fa2334f
                        at libstd/rt.rs:58
  10:     0x55a12b710943 - main
  11:     0x7fe5e7b5ff49 - __libc_start_main
  12:     0x55a12b6dbe39 - _start
  13:                0x0 - <unknown>) })', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:349
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:72
   8: core::result::unwrap_failed
   9: signal_backup_decode::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:306
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  13: std::rt::lang_start_internal
             at libstd/panicking.rs:285
             at libstd/panic.rs:361
             at libstd/rt.rs:58
  14: main
  15: __libc_start_main
  16: _start
```
Compiled with `rustc 1.26.1 (827013a31 2018-05-25)`.

**Comment by pajowu** [comment]
As the error says, there is an `MacVerificationError`. The mac is the Message Authentication Code Signal generates for every message in the backup. This usually happens if either the backup is corrupt or the passphrase is wrong. Please check that you entered the password as one large number, without spaces ("123451234512345123451234512345" instead of "12345 12345 12345 12345 12345 12345"). If the error still exists after you checked that, please reopen this issue
